http:
  routers:
    to-murdock-api:
      rule: >
        PathPrefix(`/api`) ||
        PathPrefix(`/github`) ||
        PathPrefix(`/jobs`) ||
        PathPrefix(`/job`) ||
        PathPrefix(`/results`) ||
        PathPrefix(`/ws`) ||
        PathPrefix(`/openapi.json`) ||
        PathPrefix(`/metrics`)
      service: murdock
    to-frontend:
      middlewares:
        - "replace-regex"
      rule: >
        PathPrefix(`/`) ||
        PathPrefix(`/static`)
      service: frontend
  middlewares:
    replace-regex:
      replacePathRegex:
        regex: "^/details/(.*)"
        replacement: "/"

  services:
    frontend:
      loadBalancer:
        servers:
        - url: http://murdock-frontend-{{ env "MURDOCK_PROJECT" }}:3000
    murdock:
      loadBalancer:
        servers:
        - url: http://murdock-api-{{ env "MURDOCK_PROJECT" }}:8000
